import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import {Inter as FontSans} from 'next/font/google';

import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";

const fontSans = FontSans({
  subsets:['latin'],
  variable:"--font-sans"
})

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn("min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        
        <Navbar/>
        <div className="flex">
        <div className="border bg-[#C9A857] fixed h-[100vh] w-[300px]">
           <Sidebar/>
        </div>
        <div className="p-8 bg-[#FDFBF2] mt-[80px] w-full">
        {children}
        </div>
        </div>
      </body>
    </html>
  );
}
